/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.crs;

/**
 *
 * @author konda
 */
public class CourseRecoveryPlanUI extends javax.swing.JFrame {
    private RecoveryPlan plan;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CourseRecoveryPlanUI.class.getName());

    /**
     * Creates new form CourseRecoveryPlanUI
     */
    public CourseRecoveryPlanUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStudentId = new javax.swing.JLabel();
        txtStudentId = new javax.swing.JTextField();
        btnLoadPlan = new javax.swing.JButton();
        lblCourseId = new javax.swing.JLabel();
        txtCourseId = new javax.swing.JTextField();
        lblWeek = new javax.swing.JLabel();
        txtWeek = new javax.swing.JTextField();
        lblDescription = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        lblStatus = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        btnAddTask = new javax.swing.JButton();
        btnUpdateTask = new javax.swing.JButton();
        btnDeleteTask = new javax.swing.JButton();
        btnSavePlan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTasks = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Course Recovery Plan");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblStudentId.setText("Student ID:");
        getContentPane().add(lblStudentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 70, -1, -1));
        getContentPane().add(txtStudentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 67, 71, -1));

        btnLoadPlan.setText("Load Plan");
        btnLoadPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadPlanActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoadPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 67, -1, -1));

        lblCourseId.setText("Course ID:");
        getContentPane().add(lblCourseId, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 111, -1, -1));
        getContentPane().add(txtCourseId, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 108, 71, -1));

        lblWeek.setText("Week:");
        getContentPane().add(lblWeek, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 151, 37, -1));

        txtWeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeekActionPerformed(evt);
            }
        });
        getContentPane().add(txtWeek, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 148, 71, -1));

        lblDescription.setText("Task Description:");
        getContentPane().add(lblDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 188, -1, -1));

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane2.setViewportView(txtDescription);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 210, -1, -1));

        lblStatus.setText("Status:");
        getContentPane().add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 311, 37, -1));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Started", "In Progress", "Completed", " " }));
        cmbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusActionPerformed(evt);
            }
        });
        getContentPane().add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 308, -1, -1));

        btnAddTask.setText("Add Task");
        btnAddTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTaskActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddTask, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 348, -1, -1));

        btnUpdateTask.setText("Update Task");
        btnUpdateTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTaskActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdateTask, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 348, -1, -1));

        btnDeleteTask.setText("Delete Task");
        btnDeleteTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTaskActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteTask, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 348, -1, -1));

        btnSavePlan.setText("Save Plan");
        btnSavePlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePlanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSavePlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 348, -1, -1));

        tblTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course ID ", "Week ", "Task ", "Status "
            }
        ));
        tblTasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTasksMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTasks);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 402, 460, 167));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Course Recovery Plan ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\konda\\OneDrive\\Desktop\\JAVA-COURSE-RECOVERY-SYSTEM\\CRS\\resources\\images\\Untitled design.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 270, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadPlanActionPerformed
        String student = txtStudentId.getText().trim();
String course = txtCourseId.getText().trim();

if (student.isEmpty() || course.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Enter Student ID and Course ID first!");
    return;
}

// create a new recovery plan for this student + course
plan = new RecoveryPlan(student, course);
// load existing tasks (if file exists)
plan.loadFromFile();
// refresh table
refreshTable();
javax.swing.JOptionPane.showMessageDialog(this, "Plan loaded!");

    }//GEN-LAST:event_btnLoadPlanActionPerformed

    private void txtWeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeekActionPerformed

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatusActionPerformed

    private void btnAddTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTaskActionPerformed
        if (plan == null) {
    javax.swing.JOptionPane.showMessageDialog(this, "Load a plan first");
    return;
}
String course = txtCourseId.getText().trim();
String week = txtWeek.getText().trim();
String desc = txtDescription.getText().trim();
String status = cmbStatus.getSelectedItem().toString();

RecoveryTask t = new RecoveryTask(course, week, desc, status);

boolean added = plan.addTask(t);

if (!added) {
    javax.swing.JOptionPane.showMessageDialog(this, "Invalid or duplicate task!");
    return;
}
refreshTable();
    }//GEN-LAST:event_btnAddTaskActionPerformed

    private void btnUpdateTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTaskActionPerformed
        if (plan == null) {
    javax.swing.JOptionPane.showMessageDialog(this, "Load a plan first!");
    return;
}
int index = tblTasks.getSelectedRow();
if (index == -1) {
    javax.swing.JOptionPane.showMessageDialog(this, "Select a task to update!");
    return;
}

String course = txtCourseId.getText().trim();
String week = txtWeek.getText().trim();
String desc = txtDescription.getText().trim();
String status = cmbStatus.getSelectedItem().toString();

RecoveryTask t = new RecoveryTask(course, week, desc, status);

boolean ok = plan.updateTask(index, t);

if (!ok) {
    javax.swing.JOptionPane.showMessageDialog(this, "Invalid task!");
    return;
}
refreshTable();
    }//GEN-LAST:event_btnUpdateTaskActionPerformed

    private void btnDeleteTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTaskActionPerformed
        if (plan == null) {
    javax.swing.JOptionPane.showMessageDialog(this, "Load a plan first!");
    return;
}
int index = tblTasks.getSelectedRow();
if (index == -1) {
    javax.swing.JOptionPane.showMessageDialog(this, "Select a task to delete!");
    return;
}

plan.deleteTask(index);

refreshTable();
    }//GEN-LAST:event_btnDeleteTaskActionPerformed

    private void btnSavePlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePlanActionPerformed
        if (plan == null) {
    javax.swing.JOptionPane.showMessageDialog(this, "Load a plan first!");
    return;
}
plan.saveToFile();

javax.swing.JOptionPane.showMessageDialog(this, "Plan is saved!");
    }//GEN-LAST:event_btnSavePlanActionPerformed

    private void tblTasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTasksMouseClicked
        int index = tblTasks.getSelectedRow();
    if (index != -1 && plan != null) {
        RecoveryTask t = plan.tasks.get(index);
        txtWeek.setText(t.week);
        txtDescription.setText(t.description);
        cmbStatus.setSelectedItem(t.status);
        }
    }//GEN-LAST:event_tblTasksMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CourseRecoveryPlanUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTask;
    private javax.swing.JButton btnDeleteTask;
    private javax.swing.JButton btnLoadPlan;
    private javax.swing.JButton btnSavePlan;
    private javax.swing.JButton btnUpdateTask;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCourseId;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStudentId;
    private javax.swing.JLabel lblWeek;
    private javax.swing.JTable tblTasks;
    private javax.swing.JTextField txtCourseId;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtStudentId;
    private javax.swing.JTextField txtWeek;
    // End of variables declaration//GEN-END:variables

    private void refreshTable() {
    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) tblTasks.getModel();

    // this willclear table
    model.setRowCount(0);

    // add all tasks from plan
    if (plan != null) {
        for (RecoveryTask t : plan.tasks) {
            model.addRow(new Object[]{
                t.courseId,
                t.week,
                t.description,
                t.status
            });
        }
    }
}

}
