/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crs.gui;
import crs.users.UserManager;
import javax.swing.JOptionPane;
import Email.EmailService;
import crs.gui.ResetPasswordForm;

/**
 *
 * @author skill_issue
 */
public class OTPVerificationForm extends javax.swing.JFrame {
    private UserManager manager;
    private String userEmail;
    private String userName;
    private String generatedOTP;
    private EmailService emailService = new EmailService();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OTPVerificationForm.class.getName());

    /**
     * Creates new form OTPVerificationForm
     */
   // Constructor that accepts the OTP and user info
    public OTPVerificationForm(UserManager m, String email, String name, String otp) {
        this.manager = m;
        this.userEmail = email;
        this.userName = name;
        this.generatedOTP = otp;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtOTP = new javax.swing.JTextField();
        btnVerify = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Enter OTP sent to your email");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("OTP:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 37, -1));

        txtOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOTPActionPerformed(evt);
            }
        });
        getContentPane().add(txtOTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 111, -1));

        btnVerify.setText("VERIFY");
        btnVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerify, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Slave\\OneDrive\\Desktop\\university\\year 2\\semester 01\\JAVA\\CRS\\JAVA-COURSE-RECOVERY-SYSTEM\\CRS\\resources\\images\\OTP.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 720, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOTPActionPerformed

    private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyActionPerformed
        String enteredOTP = txtOTP.getText().trim();

   if (enteredOTP.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter the OTP!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
     // Verify OTP
    if (enteredOTP.equals(generatedOTP)) {
        JOptionPane.showMessageDialog(this, "OTP Verified Successfully!");
        
        // Navigate to password reset page - PASS EMAIL
        new NewPasswordForm(manager, userEmail, userName).setVisible(true);
        this.dispose();
        
    } else {
        JOptionPane.showMessageDialog(this, "Invalid OTP! Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnVerifyActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new ResetPasswordForm(manager).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnVerify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtOTP;
    // End of variables declaration//GEN-END:variables
}
