/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crs.gui;
import crs.users.UserManager;
import Email.EmailService;
import javax.swing.*;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.Date;

public class ResetPasswordForm extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ResetPasswordForm.class.getName());
    
    private UserManager manager;
    /**
     * Creates new form ResetPasswordForm
     */
    public ResetPasswordForm() {
    initComponents();
}

    private String generatedOTP = null;
    private String userEmail = null;
    private String userName = null;
    private EmailService emailService = new EmailService();
    
    public ResetPasswordForm(UserManager m) {
        this.manager = m;
        initComponents();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(787, 446));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Enter Your email:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        btnNext.setText("NEXT");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        txtEmail.setName("emailGiven"); // NOI18N
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 184, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Slave\\OneDrive\\Desktop\\university\\year 2\\semester 01\\JAVA\\CRS\\JAVA-COURSE-RECOVERY-SYSTEM\\CRS\\resources\\images\\2.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 740, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public boolean checkEmailExists(String email) {
        try (BufferedReader reader = new BufferedReader(new FileReader("users.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] userData = line.split(",");
                
                // Format: username,email,password,role,status
                // Example: admin,admin@gmail.com,09876,admin,active
                if (userData.length >= 2) {
                    String storedEmail = userData[1].trim();
                    
                    if (storedEmail.equalsIgnoreCase(email)) {
                        userName = userData[0].trim(); // Get username for email
                        return true;
                    }
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error reading user data!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }
     
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
 String email = txtEmail.getText().trim();

    if (email.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter your email.");
        return;
    }
    
    // Check if email exists in users.txt
    if (checkEmailExists(email)) {
        userEmail = email;
        JOptionPane.showMessageDialog(this, "Email found! Proceeding to OTP verification...");
        
        // Generate and send OTP
        generatedOTP = emailService.generateOTP();
        emailService.sendPasswordResetOTP(userEmail, userName, generatedOTP);
        
        JOptionPane.showMessageDialog(this, "OTP has been sent to your email!");
        
        // Navigate to OTP page - PASS ALL REQUIRED DATA
        new OTPVerificationForm(manager, userEmail, userName, generatedOTP).setVisible(true);
        this.dispose();
        
    } else {
        JOptionPane.showMessageDialog(this, "Email not found in the system!", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new LoginForm(manager).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}