
package crs.ui;
import java.util.List;
import crs.model.Student;
import crs.model.Course;
import crs.model.CourseResult;
import crs.model.CourseRegistry;
import crs.file.DataLoader;
import javax.swing.table.DefaultTableModel;
import crs.report.AcademicReportGenerator;
import javax.swing.JOptionPane;


/**
 *
 * @author Ahmed
 * 
 
 */
public class ReportUI extends javax.swing.JFrame {
    private List<Student> students;

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportUI.class.getName());

    

    public ReportUI() {
        initComponents();
        
        // Load data
students = DataLoader.loadStudents("data/student_information.csv");
DataLoader.loadCourses("data/course_assessment_information.csv");
DataLoader.loadResults("data/course_results.csv", students);

// Populate combo box
student.removeAllItems();
for (Student s : students) {
    student.addItem(s.getStudentId() + " - " + s.getFullName());
}


// When student is selected → update UI
student.addActionListener(e -> {
    updateStudentDetails();
    updateTableResults();
});

// Auto-load first student
if (!students.isEmpty()) {
    student.setSelectedIndex(0);
    updateStudentDetails();
    updateTableResults();
}

    }

    private void updateStudentDetails() {
    Student s = getSelectedStudent();
    if (s == null) return;

    lblName.setText("Name: " + s.getFullName());
    lblID.setText("ID: " + s.getStudentId());
    lblMajor.setText("Major: " + s.getMajor());
    lblYear.setText("Year: " + s.getStudyYear());
    lblEmail.setText("Email: " + s.getEmail());
}

    private Student getSelectedStudent() {
    int index = student.getSelectedIndex();
    if (index < 0) return null;
    return students.get(index);  // SAME ORDER as combo-box
}

    
    
    
    
private void updateTableResults() {
    Student s = getSelectedStudent();
    if (s == null) return;

    DefaultTableModel model = (DefaultTableModel) tableResults.getModel();
    model.setRowCount(0);

    for (CourseResult r : s.getCourseResults()) {
        Course c = CourseRegistry.getCourse(r.getCourseId());
        model.addRow(new Object[]{
            r.getCourseId(),
            c != null ? c.getCourseName() : "Unknown",
            r.getFinalMark(),
            r.getGrade(),
            r.isPassed() ? "Yes" : "No"
        });
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        lblName = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblMajor = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        scrollResults = new javax.swing.JScrollPane();
        tableResults = new javax.swing.JTable();
        student = new javax.swing.JComboBox<>();
        btnGeneratePDF = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label1.setName(""); // NOI18N
        label1.setText("Select Student");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        label1.getAccessibleContext().setAccessibleDescription("");
        label1.getAccessibleContext().setAccessibleParent(label1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("label2");

        lblName.setForeground(new java.awt.Color(0, 0, 0));
        lblName.setText("Name : ");

        lblID.setBackground(new java.awt.Color(255, 255, 255));
        lblID.setForeground(new java.awt.Color(0, 0, 0));
        lblID.setText("ID : ");

        lblMajor.setForeground(new java.awt.Color(0, 0, 0));
        lblMajor.setText("Major :");

        lblYear.setForeground(new java.awt.Color(0, 0, 0));
        lblYear.setText("Year : ");

        lblEmail.setForeground(new java.awt.Color(0, 0, 0));
        lblEmail.setText("Email : ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblMajor)
                            .addComponent(lblYear)
                            .addComponent(lblEmail))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(706, 706, 706))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMajor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblYear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEmail))
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 173, 243, -1));

        tableResults.setBackground(new java.awt.Color(255, 255, 255));
        tableResults.setForeground(new java.awt.Color(0, 0, 0));
        tableResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Course ID ", "Course Name", "Final Mark", "Mark", "Grade"
            }
        ));
        tableResults.setName(""); // NOI18N
        scrollResults.setViewportView(tableResults);

        jPanel1.add(scrollResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 646, 379));

        student.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentActionPerformed(evt);
            }
        });
        jPanel1.add(student, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 115, 313, 30));

        btnGeneratePDF.setBackground(new java.awt.Color(255, 255, 255));
        btnGeneratePDF.setForeground(new java.awt.Color(0, 0, 0));
        btnGeneratePDF.setText("Generate PDF Report");
        btnGeneratePDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneratePDFActionPerformed(evt);
            }
        });
        jPanel1.add(btnGeneratePDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, 335, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Course Summry");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 199, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ahmed\\Downloads\\Untitled design.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, -60, 290, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentActionPerformed


        // TODO add your handling code here:
    }//GEN-LAST:event_studentActionPerformed

    private void btnGeneratePDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneratePDFActionPerformed
                                              
    Student s = getSelectedStudent();
    if (s == null) {
        JOptionPane.showMessageDialog(this, "No student selected!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        // Create folder if missing
        String folder = "reports/";
        java.io.File dir = new java.io.File(folder);
        if (!dir.exists()) dir.mkdirs();

        // File name
        String filename = folder + "Report_" + s.getStudentId() + ".pdf";

        // Generate PDF
        new AcademicReportGenerator().generate(s, filename);

        JOptionPane.showMessageDialog(this,
                "PDF generated successfully:\n" + filename,
                "Success",
                JOptionPane.INFORMATION_MESSAGE
        );

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                "Failed to generate PDF.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
        ex.printStackTrace();
    }


    }//GEN-LAST:event_btnGeneratePDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReportUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGeneratePDF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMajor;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblYear;
    private javax.swing.JScrollPane scrollResults;
    private javax.swing.JComboBox<String> student;
    private javax.swing.JTable tableResults;
    // End of variables declaration//GEN-END:variables
}
